name: Java CI to create and upload release on pull request
on:
  pull_request:
    types:
      - closed
    branches: ["main"]

permissions:
  contents: write

# Jobs that will execute
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    release:
      name: Setup Environment, Build JAR and Release Project
      runs-on: ubuntu-latest
      steps:
        - name: Automatic Release
          uses: NolanKnight/java-automatic-release@v3
          with:
            java-version: 17
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPOSITORY_NAME: ${{ github.event.repository.name }}
            # Message specified in the commit
            COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
            FILES: app/build/libs/app-1.0.0-all.jar
